### ISSUE TITLE
EXTRINSIC_FAILED error from balanceTransfer

### ISSUE THREAD

**Issue by ogous** [capsule-corp-ternoa/ternoa-js#101]
### Describe the bug

balanceTransfer method does not work and throws this error:

```
Error: EXTRINSIC_FAILED
    at BlockchainEvents.findEventOrThrow (/Users/oguzhanali/Development/mafiafoot/node_modules/ternoa-js/events.js:823:19)
    at /Users/oguzhanali/Development/mafiafoot/node_modules/ternoa-js/balance/extrinsics.js:90:46
    at step (/Users/oguzhanali/Development/mafiafoot/node_modules/ternoa-js/balance/extrinsics.js:33:23)
    at Object.next (/Users/oguzhanali/Development/mafiafoot/node_modules/ternoa-js/balance/extrinsics.js:14:53)
    at fulfilled (/Users/oguzhanali/Development/mafiafoot/node_modules/ternoa-js/balance/extrinsics.js:5:58)
```

### To reproduce

```
 await initializeApi(WSS)
 const keyring = await getKeyringFromSeed(SEED)
 const response = await balancesTransfer(
     WALLETID,
     1,
     keyring,
     0,
    )
```    

### Expected behavior

As document declares: https://ternoa-js.ternoa.dev/modules.html#balancesTransfer

**Comment by ogous** [comment]
This issue is resolved spontaneously this morning, after first encounter last night.

**Comment by ipapandinas** [comment]
The execution flow is properly sequenced.
